### ISSUE TITLE
Can I start this game on (or in) linux

### ISSUE THREAD

**Issue by win64** [Lioncat2002/SeasonsPlatformer#1]
Information in title. I write it from 2 hours bus travel. I have a kubuntu ([https://kubuntu.org](url)) 21.04.
Sorry for my english :)

**Comment by Lioncat2002** [comment]
Hello, Thanks for asking :)
I haven't really tested on any linux distros
but I don't think there should be any trouble since there isn't any platform specific code

**Comment by win64** [comment]
ok, i try to compile it in virtualbox(or qemu), thanks for response :D

**Comment by Lioncat2002** [comment]
> ok, i try to compile it in virtualbox(or qemu), thanks for response :D

Did it work?

**Comment by win64** [comment]
Oh sorry, yes it works
